FACEBOOK_APP_ID: 417365406996462
FACEBOOK_APP_SECRET: 69fcdf51e4fc06108af5397f48dd247f
GOOGLE_CLIENT_ID: 979276625045-jvgnpca688p6rfdqsom1fiiol61sk9bh.apps.googleusercontent.com
GOOGLE_CLIENT_SECRET: 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
